#!/bin/bash
#Author: NerdOfCode
#Purpose: Adds a few alias's that improve the efficieny of your terminal
#Tested: Linux Mint 18.1 Serena | Kernel Version 4.4.0-79-generic

#Storage for alias's
storage='.1bashrc'
shrt_alias=("content" "kernel")


function available_commands(){
	for i in "${shrt_alias[@]}"
	do
        echo $i
done

}


function add_shortcuts(){
	if [ -f ~/$storage ]
	then
		echo "Please delete $storage and try again"
		exit 1
	fi


	echo -e "Adding\n"
	echo -e '#!/bin/bash\n' | tee -a ~/$storage
	echo -e '#Author: NerdOfCode' | tee -a ~/$storage
	echo -e '#Auto Generated by bashrc_alias.sh' | tee -a ~/$storage
	echo 'alias content="grep -R $1"' | tee -a ~/$storage
	echo 'alias kernel="uname -r"' | tee -a ~/$storage
	source ~/$storage
	sleep 2
	echo ""

  	exit 0;}
function remove_shortcuts(){

	if [ -f ~/$storage ]
	then
		echo -e "Removing\n"
		rm $storage
  		exit 0
	fi
	echo "The shortcuts arent installed"
	exit 1;}
function options(){
	case $response in
        	"1") 
                	add_shortcuts;;
        	"2")
                	remove_shortcuts;;
        	"4")
                	echo "Good bye";exit;;
		"3")
			available_commands;;
        	*)
                	echo "Unknown option selected";;
	esac
}


clear
while :
do
	echo -e "1)Add the shortcuts \n2)Remove the shortcuts\n3)Show available alias's\n4)Exit"
	read -p "Response: " response
	options
	sleep 3
	clear

done
